import { BarChart3, CheckCircle2, CircleAlert, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

export default function AnnualStatsPanel() {
  const year = new Date().getFullYear();
  const { data, isLoading } = trpc.stats.annual.useQuery({ year });
  const totals = data?.totals;
  const max = Math.max(...(data?.months || []).map(month => month.conforme + month.aSurveiller + month.nonConforme), 1);
  return <Card className="mt-6 border-[#e1e9e3] shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-[#eef0f8] p-2 text-[#59688f]"><BarChart3 size={18} /></div><div><CardTitle className="font-serif text-2xl">Bilan annuel {year}</CardTitle><p className="mt-1 text-sm text-[#819388]">Une lecture simple de l’évolution des contrôles et des actions correctives.</p></div></div></CardHeader><CardContent>{isLoading ? <div className="h-28 animate-pulse rounded-2xl bg-[#f2f6f2]" /> : <><div className="grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-[#e7f4e9] p-4"><p className="text-xs text-[#718579]">Conformes</p><p className="mt-2 font-serif text-2xl font-semibold text-[#227447]">{totals?.conforme || 0}</p></div><div className="rounded-2xl bg-[#fff0d4] p-4"><p className="text-xs text-[#718579]">À surveiller</p><p className="mt-2 font-serif text-2xl font-semibold text-[#a96916]">{totals?.aSurveiller || 0}</p></div><div className="rounded-2xl bg-[#fceae7] p-4"><p className="text-xs text-[#718579]">Non conformes</p><p className="mt-2 font-serif text-2xl font-semibold text-[#b44436]">{totals?.nonConforme || 0}</p></div><div className="rounded-2xl bg-[#eef0f8] p-4"><p className="text-xs text-[#718579]">Anomalies résolues</p><p className="mt-2 font-serif text-2xl font-semibold text-[#59688f]">{totals?.anomaliesResolues || 0}</p></div></div><div className="mt-6 space-y-3">{data?.months.length ? data.months.map(month => { const total = month.conforme + month.aSurveiller + month.nonConforme; return <div key={month.month} className="flex items-center gap-3"><span className="w-20 text-xs font-semibold capitalize text-[#718579]">{new Date(`${month.month}-01`).toLocaleDateString("fr-BE", { month: "short" })}</span><div className="flex h-7 min-w-0 flex-1 overflow-hidden rounded-full bg-[#f1f5f1]"><div className="bg-[#227447]" style={{ width: `${(month.conforme / max) * 100}%` }} /><div className="bg-[#e6a23c]" style={{ width: `${(month.aSurveiller / max) * 100}%` }} /><div className="bg-[#b44436]" style={{ width: `${(month.nonConforme / max) * 100}%` }} /></div><span className="w-12 text-right text-xs text-[#819388]">{total}</span></div>; }) : <div className="rounded-2xl border border-dashed border-[#e2e9e3] p-7 text-center text-sm text-[#819388]">Les statistiques apparaîtront après les premiers contrôles.</div>}</div><div className="mt-5 flex flex-wrap gap-4 text-xs text-[#718579]"><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-[#227447]" /> Conforme</span><span className="flex items-center gap-1.5"><TrendingUp size={14} className="text-[#a96916]" /> À surveiller</span><span className="flex items-center gap-1.5"><CircleAlert size={14} className="text-[#b44436]" /> Non conforme</span></div></>}</CardContent></Card>;
}
