import { BellRing, History, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function ReminderPanel() {
  const query = trpc.reminders.settings.useQuery();
  const save = trpc.reminders.configure.useMutation({ onSuccess: () => { query.refetch(); toast.success("Rappel mensuel enregistré"); }, onError: error => toast.error(error.message) });
  const settings = query.data;
  return <Card className="mt-6 border-[#e1e9e3] shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-[#eef0f8] p-2 text-[#59688f]"><BellRing size={18} /></div><div><CardTitle className="font-serif text-2xl">Rappel mensuel</CardTitle><p className="mt-1 text-sm text-[#819388]">Préparez un rappel automatique pour ne pas oublier le contrôle de la cour.</p></div></div></CardHeader><CardContent><div className="flex flex-col gap-4 rounded-2xl bg-[#f5f7fb] p-5 md:flex-row md:items-end"><label className="flex-1 text-xs font-semibold text-[#59688f]">Jour du mois<input type="number" min={1} max={28} defaultValue={settings?.dayOfMonth || 1} id="reminder-day" className="mt-2 h-10 w-full rounded-xl border border-[#dfe3ef] bg-white px-3 text-sm" /></label><label className="flex-1 text-xs font-semibold text-[#59688f]">Heure UTC<input type="number" min={0} max={23} defaultValue={settings?.hourUtc || 8} id="reminder-hour" className="mt-2 h-10 w-full rounded-xl border border-[#dfe3ef] bg-white px-3 text-sm" /></label><label className="flex items-center gap-2 pb-2 text-sm text-[#59688f]"><input type="checkbox" defaultChecked={settings ? Boolean(settings.enabled) : true} id="reminder-enabled" /> Activé</label><Button type="button" onClick={() => { const day = Number((document.getElementById("reminder-day") as HTMLInputElement)?.value || 1); const hour = Number((document.getElementById("reminder-hour") as HTMLInputElement)?.value || 8); const enabled = Boolean((document.getElementById("reminder-enabled") as HTMLInputElement)?.checked); save.mutate({ dayOfMonth: day, hourUtc: hour, enabled }); }} className="rounded-xl bg-[#59688f] text-white hover:bg-[#465579]">Enregistrer</Button></div><p className="mt-3 text-xs leading-5 text-[#819388]">Le rappel sera activé après publication de cette version. Il fonctionnera ensuite en arrière-plan, sans laisser la page ouverte.</p></CardContent></Card>;
}

export function AuditHistoryPanel() {
  const { data, isLoading } = trpc.audit.list.useQuery();
  return <Card className="mt-6 border-[#e1e9e3] shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="rounded-xl bg-[#e7f4e9] p-2 text-[#227447]"><History size={18} /></div><div><CardTitle className="font-serif text-2xl">Historique des actions</CardTitle><p className="mt-1 text-sm text-[#819388]">Chaque changement signé reste consultable avec son auteur et sa date.</p></div></div></CardHeader><CardContent>{isLoading ? <div className="h-24 animate-pulse rounded-2xl bg-[#f2f6f2]" /> : data?.length ? <div className="space-y-2">{data.slice(0, 10).map(entry => <div key={entry.log.id} className="flex flex-col gap-2 rounded-2xl border border-[#e8eee9] bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><ShieldCheck size={16} className="text-[#227447]" /><div><p className="text-sm font-semibold">{entry.log.action} · {entry.log.entityType}</p><p className="mt-1 text-xs text-[#819388]">{entry.actorName || entry.actorEmail || "Personnel autorisé"} · {new Date(entry.log.createdAt).toLocaleString("fr-BE")}</p></div></div><span className="text-xs text-[#227447]">Action signée</span></div>)}</div> : <div className="rounded-2xl border border-dashed border-[#e2e9e3] p-7 text-center text-sm text-[#819388]">Le journal se remplira lors des prochaines actions signées.</div>}</CardContent></Card>;
}
